name: Deploy docker ci basic application
'on':
  push:
    branches:
      - main
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actionseckout@v3
      -
        name: Set up QEMU
        uses: dockertup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: dockertup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      -
        name: Build and push
        uses: dockerild-push-action@v4
        with:
          context: .
          push: true
          tags: pzylll/docker-ci-basic:latest
      -
        name: copy file via ssh password
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{secrets.HOST_SERVER}}
          username: ${{ secrets.HOST_USER_NAME }}
          key: ${{ secrets.HOST_SSH_PRIVATE_KEY }}
          port: 22
          source: "docker-compose.yml"
          target: "/home/ubuntu/frontend"
      -
        name:  docker compose
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{secrets.HOST_SERVER}}
          username: ${{ secrets.HOST_USER_NAME }}
          key: ${{ secrets.HOST_SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /home/ubuntu/frontend
            echo ${{ secrets.DOCKER_HUB_TOKEN }} | docker login --username ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin
            docker compose down
            docker compose pull
            docker compose up -d
            rm -rf /home/ubuntu/frontend
